name: codechecker-tests

# Triggers the workflow on push or pull request events.
on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyzer:
    name: Analysis
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 6.5.0

      - name: Install dependencies
        run: sh .github/workflows/install-deps.sh

      # TODO: Consider using top-of-the-tree CodeChecker as well.
      - name: Install CodeChecker
        run: |
          pip3 install codechecker
          CodeChecker version

      - name: Run analyzer tests
        working-directory: test/
        run: python -m unittest discover . -vvv
